baseURL = "https://storopoli.io/"
languageCode = "en-us"
theme = "WonderMod"
title = "Jose Storopoli, PhD"
copyright = "[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableGitInfo = true

[permalinks]
posts = "/:filename"

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Jose Storopoli, PhD"
description = "I make computers go brrr faster with Rust, Julia and Nix"
keywords = [
  "statistics",
  "Bayesian statistics",
  "Julia",
  "Rust",
  "math",
  "blog",
  "research",
  "security",
  "privacy",
]
author = "Jose Storopoli"
DateFormat = "January 2, 2006"
defaultTheme = "dark" # dark, light
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowFullTextinRSS = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

[params.assets]
disableHLJS = true
disableFingerprinting = false
favicon = "/assets/favicon.ico"

[params.profileMode]
enabled = true
Subtitle = "I make computers go brrr faster with Rust, Julia and Nix"
imageUrl = "/assets/pp.jpeg"
imageTitle = "Profile Pic"

[[params.socialIcons]]
name = "cv"
url = "https://github.com/storopoli/cv/releases/latest/download/cv.pdf"

[[params.socialIcons]]
name = "github"
url = "https://github.com/storopoli"

[[params.socialIcons]]
name = "email"
url = "mailto:jose@storopoli.io"

[[params.socialIcons]]
name = "pgpkey"
url = "/assets/publickey.txt"

[[params.socialIcons]]
name = "rss"
url = "index.xml"

[params.cover]
hidden = true
hiddenInList = true
hiddenInSingle = true

[params.editPost]
URL = "https://github.com/storopoli/storopoli.github.io/blob/main/content"
Text = "Source code"
appendFilePath = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "summary"]

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.highlight]
style = "dracula"
noClasses = false
guessSyntax = true

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "posts/"
weight = 10

[[menu.main]]
identifier = "cv"
name = "CV"
url = "https://github.com/storopoli/cv/releases/latest/download/cv.pdf"
weight = 10

[[menu.main]]
identifier = "search"
name = "Search"
url = "search/"
weight = 20
