// Shared chrome, show rules, and body rendering for storopoli.com.
// Every compile/query must pass: --root <repo> --features html
// Markdown is converted to typst markup by pandoc (scripts/body-filter.lua)
// in build.sh; the wrappers eval the generated body with the helpers below.

#let site-title = "Jose Storopoli, PhD"
#let site-url = "https://storopoli.com"

// YAML dates arrive as datetime, frontmatter strings as str; normalize to ISO.
// Dates display as ISO everywhere (mono "terminal chrome" style).
#let date-iso(date) = if type(date) == datetime {
  date.display("[year]-[month]-[day]")
} else {
  str(date)
}

#let slugify(s) = lower(s).replace(" ", "-")

// Math is exported as native MathML by Typst 0.15: accessible, selectable,
// scales with zoom/font-size, ~90% smaller than inline SVG, and inherits the
// surrounding text color for free (so light/dark mode needs no repainting).
// `<math>` carries an implicit ARIA role, so no wrapper element is needed;
// styling lives on the `math` element in site.css.
#let setup(doc) = {
  set text(lang: "en")
  doc
}

// Site header, main, and footer emitted inside typst's default <body>.
// A custom <html>/<body> element would break native footnotes, so the
// remaining <head> links are injected by scripts/build.sh instead.
// Skipped entirely outside HTML export: `typst query` (used for the
// frontmatter metadata) runs paged export, which would warn about every
// top-level html.elem.
#let chrome(is-post: false, body) = context if target() == "html" {
  // Posts get a reading-progress bar on the sticky header (site.css).
  html.elem("header", attrs: if is-post { (class: "post-header") } else { (:) }, {
    // CSS-only light/dark toggle: site.css flips color-scheme when checked
    html.elem("input", attrs: (
      type: "checkbox",
      id: "theme-toggle",
      class: "theme-toggle",
      "aria-label": "Toggle light/dark theme",
    ))
    html.elem("div", attrs: (class: "logo"), html.elem("a", attrs: (href: "/"), site-title))
    html.elem("nav", {
      html.elem("a", attrs: (href: "/"), "Home")
      html.elem("a", attrs: (href: "/about.html"), "About")
      html.elem("a", attrs: (href: "/contact.html"), "Contact")
      html.elem("a", attrs: (href: "/archive.html"), "Archive")
      html.elem("a", attrs: (href: "/atom.xml"), "RSS")
      html.elem("label", attrs: (
        "for": "theme-toggle",
        class: "theme-label",
        title: "Toggle light/dark theme",
      ), "◐")
    })
  })
  html.elem("main", attrs: (role: "main"), body)
  html.elem("footer", {
    if is-post {
      html.elem("a", attrs: (href: "#"), "↑ Go to top")
      " · "
    }
    html.elem("a", attrs: (href: "/atom.xml"), "rss")
    " · "
    html.elem("a", attrs: (href: "https://github.com/storopoli/storopoli.com"), "Website source")
    " · Site proudly generated by "
    html.elem("a", attrs: (href: "https://typst.app"), "Typst")
    " and "
    html.elem("a", attrs: (href: "https://pandoc.org"), "Pandoc")
  })
}

// Markdown image: real <img> reference (typst's image() would embed the
// file as a base64 data URI) with the alt text doubling as a caption.
#let md-img(src, alt: "") = html.elem("figure", {
  html.elem("img", attrs: (src: src, alt: alt, loading: "lazy"))
  if alt != "" {
    html.elem("figcaption", alt)
  }
})

// Raw <img> passthrough (about page profile picture keeps its class).
#let raw-img(src, alt: "", class: "") = html.elem("img", attrs: (
  src: src,
  alt: alt,
  class: class,
  loading: "lazy",
))

// Privacy-hardened YouTube embed; styling lives in site.css.
#let youtube(id) = html.elem(
  "div",
  attrs: (class: "embed-container"),
  html.elem("iframe", attrs: (
    src: "https://www.youtube-nocookie.com/embed/" + id,
    title: "YouTube video player",
    frameborder: "0",
    loading: "lazy",
    referrerpolicy: "strict-origin-when-cross-origin",
    sandbox: "allow-scripts allow-same-origin allow-presentation",
    allowfullscreen: "",
  )),
)

// Evaluate a pandoc-generated typst body with the helpers in scope.
#let render-body(path) = eval(read(path), mode: "markup", scope: (
  md-img: md-img,
  raw-img: raw-img,
  youtube: youtube,
  // pandoc emits #horizontalrule for markdown thematic breaks; its
  // standalone template normally defines it
  horizontalrule: html.elem("hr"),
  // pandoc centers tables with align(center)[...], which typst's HTML
  // export ignores (with a warning); unwrap it and let CSS center tables
  align: (alignment, body) => body,
))
