// Shared chrome, show rules, and markdown rendering for storopoli.com.
// Every compile/query must pass: --root <repo> --features html

#import "@preview/cmarker:0.1.6"

#let site-title = "Jose Storopoli, PhD"
#let site-url = "https://storopoli.com"

#let months = (
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
)

// YAML dates arrive as datetime, frontmatter strings as str; normalize to ISO.
#let date-iso(date) = if type(date) == datetime {
  date.display("[year]-[month]-[day]")
} else {
  str(date)
}

// "2024-02-05" -> "February 5, 2024" (Hakyll's %B %e, %Y)
#let display-date(date) = {
  let parts = date-iso(date).split("-")
  months.at(int(parts.at(1)) - 1) + " " + str(int(parts.at(2))) + ", " + parts.at(0)
}

#let slugify(s) = lower(s).replace(" ", "-")

// Show rules for HTML export: math as inline SVG frames, gruvbox raw theme.
// Math would otherwise be silently dropped by typst's HTML export.
#let setup(doc) = {
  set text(lang: "en")
  set raw(theme: "/themes/gruvbox-dark.tmTheme")
  show math.equation.where(block: false): it => html.elem(
    "span",
    attrs: (class: "math-inline", role: "math"),
    html.frame(it),
  )
  show math.equation.where(block: true): it => html.elem(
    "div",
    attrs: (class: "math-display", role: "math"),
    html.frame(it),
  )
  doc
}

// Site header, main, and footer emitted inside typst's default <body>.
// A custom <html>/<body> element would break native footnotes, so the
// remaining <head> links are injected by scripts/build.sh instead.
#let chrome(is-post: false, body) = {
  html.elem("header", {
    html.elem("div", attrs: (class: "logo"), html.elem("a", attrs: (href: "/"), site-title))
    html.elem("nav", {
      html.elem("a", attrs: (href: "/"), "Home")
      html.elem("a", attrs: (href: "/about.html"), "About")
      html.elem("a", attrs: (href: "/contact.html"), "Contact")
      html.elem("a", attrs: (href: "/archive.html"), "Archive")
      html.elem("a", attrs: (href: "/atom.xml"), "RSS")
    })
  })
  html.elem("main", attrs: (role: "main"), body)
  html.elem("footer", {
    if is-post {
      html.elem("a", attrs: (href: "#"), "↑ Go to top")
      " | "
    }
    html.elem("a", attrs: (href: "/atom.xml", class: "small-caps"), "rss")
    " | "
    html.elem("a", attrs: (href: "https://github.com/storopoli/storopoli.com"), "Website source")
    " | Site proudly generated by "
    html.elem("a", attrs: (href: "https://typst.app"), "Typst")
  })
}

// CommonMark -> content. Math inside $...$/$$...$$ is typst math syntax.
#let render-md(src) = cmarker.render(
  src,
  math: (it, block: false) => if block {
    eval("$ " + it + " $")
  } else {
    eval("$" + it + "$")
  },
  h1-level: 1,
  scope: (
    // Reference images instead of cmarker's default #image(), which would
    // embed them as base64 data URIs and resolve paths against the package.
    image: (src, alt: none) => html.elem("img", attrs: (
      src: src,
      alt: if alt == none { "" } else { alt },
      loading: "lazy",
    )),
  ),
  html: (
    div: (attrs, body) => html.elem("div", attrs: attrs, body),
    span: (attrs, body) => html.elem("span", attrs: attrs, body),
    blockquote: (attrs, body) => html.elem("blockquote", attrs: attrs, body),
    footer: (attrs, body) => html.elem("footer", attrs: attrs, body),
    cite: (attrs, body) => html.elem("cite", attrs: attrs, body),
    iframe: ("raw-text", (attrs, body) => html.elem("iframe", attrs: attrs, body)),
    img: ("void", (attrs) => html.elem("img", attrs: attrs)),
    br: ("void", (attrs) => html.elem("br")),
    // Embed styling lives in site.css and the site ships no JavaScript.
    style: ("raw-text", (attrs, body) => none),
    script: ("raw-text", (attrs, body) => none),
  ),
)
