name: Links Check
# runs every monday at 9 am
on:
  schedule:
    - cron: "0 9 * * 1"
  workflow_dispatch: null

permissions: {}

jobs:
  check-links:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Typst
        uses: typst-community/setup-typst@63ac138db421d586de61f7f5ac3bcef6a2e6c78c # v5.1.0
        with:
          typst-version: "0.15.0"

      - name: Install Pandoc
        uses: pandoc/actions/setup@86321b6dd4675f5014c611e05088e10d4939e09e # v1.1.1
        with:
          version: "3.9.0.2"

      - name: Build site
        run: ./scripts/build.sh

      - name: Check all links in built site
        uses: lycheeverse/lychee-action@8646ba30535128ac92d33dfc9133794bfdd9b411 # v2.8.0
        with:
          args: --config lychee.toml --root-dir "${{ github.workspace }}/_site" --no-progress "_site"
          fail: true
