name: Test build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  test:
    name: Test Site Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Zola Build
        uses: shalzz/zola-deploy-action@v0.20.0
        env:
          BUILD_ONLY: true

      - name: Zola Check
        uses: shalzz/zola-deploy-action@v0.20.0
        env:
          BUILD_ONLY: true
          CHECK_LINKS: true
